### ISSUE TITLE
Process dies when ethers hits nonce error

### ISSUE THREAD

**Issue by JoeHowarth** [wormhole-foundation/relayer-engine#52]
### Problem
If there is a nonce collision (or presumably other tx failure modes), ethers throws and nothing catches it, resulting in the process dying. Not sure how this happens since all actions are executed inside a try catch. 

unhelpful stacktrace
```
2023-01-27 15:18:40.050|debug|executorHarness: No new workflows found
/Users/jh/work/wormhole/trustless-generic-relayer/relayer_engine/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
Error: transaction was replaced [ See: https://links.ethers.org/v5-errors-TRANSACTION_REPLACED ] (cancelled=true, reason="replaced", replacement={"hash":"0x13628d7ecc019c6e26e8936a34d59e344420906874c2f44c656680cad72b59db","type":2,"accessList":[],"blockHash":"0x3bb1b9536b9ba2cfdafc4a672fd3307b1ef7a741f822c9b17ea517368e6cc5bd","blockNumber":18392691,"transactionIndex":0,"confirmations":4,"from":"0x61a51662f0B30Bf176484cAc5B4a033C497cB2f3","gasPrice":{"type":"BigNumber","hex":"0x062b85e900"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x0bfda3a300"},"gasLimit":{"type":"BigNumber","hex":"0x2dc6c0"},"to":"0x7903B8CE0FF4480e1c2496123b6623858be738e0","value":{"type":"BigNumber","hex":"0xd529b0f291e464"},"nonce":6055,"data":"0x8166b60c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000007903b8ce0ff4480e1c2496123b6623858be738e000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000870100000000010076953fc025262be801edb15380c193d7afaa03e81a93c7de70d5f543a146608b73e6fdf0800b212dbb81a9a6b0a5a84d307b5c35cb9a1bd48e182777bb5c35190063d44dae0000000100040000000000000000000000000bc36d19a88341795d69535d3f977db773ecd5f40000000000000006c80048656c6c6f20576f726c6400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012501000000000100cc4ae5223e4c6199f413aee74fbed55930933dfad5c35bcbecdf994ca23da17576fe0eeb8bb3a3ed9c0eb56cec9e9f707a2e0768c192e7212ea8939e57de54c90163d44dae000000010004000000000000000000000000ac9ef19ab4f9a3a265809df0c4eb1e821f43391a0000000000000006c80101010006000000000000000000000000fe0058b9e4df432cc3dbf7ba4f97369ff1731002000000000000000000000000fe0058b9e4df432cc3dbf7ba4f97369ff173100200000000000000000000000000000000000000000000000000d529b0f291e400000000000000000000000000000000000000000000000000000000000000000001001e84800000000000000000000000007903b8ce0ff4480e1c2496123b6623858be738e0000000000000000000000000000000000000000000000000000000","r":"0x79c55f7b33210a1098e5d72a6481b5762003b2f5a6349864ee8097b1ff9bd440","s":"0x3054093afd32637a9516752c3c29585d5e165772b6b5e4e5517f4c4b19302f3b","v":0,"creates":null,"chainId":43113}, hash="0x958e30ecbd90a4405616bfd3af6cb4f77f6a30852b174dccaadffcb6f505acac", receipt={"to":"0x7903B8CE0FF4480e1c2496123b6623858be738e0","from":"0x61a51662f0B30Bf176484cAc5B4a033C497cB2f3","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x032d5d"},"logsBloom":"0x00004000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000400000800100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000002000000000000000000000000000000000000000000000000000000400000000000000000000008000080000000000000000000000000000000020000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000001000000000001000","blockHash":"0x3bb1b9536b9ba2cfdafc4a672fd3307b1ef7a741f822c9b17ea517368e6cc5bd","transactionHash":"0x13628d7ecc019c6e26e8936a34d59e344420906874c2f44c656680cad72b59db","logs":[{"transactionIndex":0,"blockNumber":18392691,"transactionHash":"0x13628d7ecc019c6e26e8936a34d59e344420906874c2f44c656680cad72b59db","address":"0x9Dfd308e2450b26290d926Beea2Bb4F0B8553729","topics":["0x21144b36c42682de3e5cbd8fae7f84a0a6cdfaefe7feb96a4dec870645c65f29","0xb63179adaf190abd0be302c751fb55d7a753c2bad340182d6939779c443c1fc1","0x000000000000000000000000fe0058b9e4df432cc3dbf7ba4f97369ff1731002","0x0000000000000000000000000000000000000000000000000000000000000006"],"data":"0x0000000000000000000000000000000000000000000000000000000000000004","logIndex":0,"blockHash":"0x3bb1b9536b9ba2cfdafc4a672fd3307b1ef7a741f822c9b17ea517368e6cc5bd"}],"blockNumber":18392691,"confirmations":4,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x032d5d"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x062b85e900"},"status":1,"type":2,"byzantium":true}, code=TRANSACTION_REPLACED, version=providers/5.7.2)
    at Logger.makeError (/Users/jh/work/wormhole/trustless-generic-relayer/relayer_engine/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at JsonRpcProvider.<anonymous> (/Users/jh/work/wormhole/trustless-generic-relayer/relayer_engine/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1380:55)
    at step (/Users/jh/work/wormhole/trustless-generic-relayer/relayer_engine/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/jh/work/wormhole/trustless-generic-relayer/relayer_engine/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/jh/work/wormhole/trustless-generic-relayer/relayer_engine/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'replaced',
  code: 'TRANSACTION_REPLACED',
  cancelled: true,
  replacement: {
    hash: '0x13628d7ecc019c6e26e8936a34d59e344420906874c2f44c656680cad72b59db',
    type: 2,
    accessList: [],
    blockHash: '0x3bb1b9536b9ba2cfdafc4a672fd3307b1ef7a741f822c9b17ea517368e6cc5bd',
    blockNumber: 18392691,
    transactionIndex: 0,
    confirmations: 4,
    from: '0x61a51662f0B30Bf176484cAc5B4a033C497cB2f3',
    gasPrice: BigNumber { _hex: '0x062b85e900', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x0bfda3a300', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x2dc6c0', _isBigNumber: true },
    to: '0x7903B8CE0FF4480e1c2496123b6623858be738e0',
    value: BigNumber { _hex: '0xd529b0f291e464', _isBigNumber: true },
    nonce: 6055,
    data: '0x8166b60c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000007903b8ce0ff4480e1c2496123b6623858be738e000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000870100000000010076953fc025262be801edb15380c193d7afaa03e81a93c7de70d5f543a146608b73e6fdf0800b212dbb81a9a6b0a5a84d307b5c35cb9a1bd48e182777bb5c35190063d44dae0000000100040000000000000000000000000bc36d19a88341795d69535d3f977db773ecd5f40000000000000006c80048656c6c6f20576f726c6400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012501000000000100cc4ae5223e4c6199f413aee74fbed55930933dfad5c35bcbecdf994ca23da17576fe0eeb8bb3a3ed9c0eb56cec9e9f707a2e0768c192e7212ea8939e57de54c90163d44dae000000010004000000000000000000000000ac9ef19ab4f9a3a265809df0c4eb1e821f43391a0000000000000006c80101010006000000000000000000000000fe0058b9e4df432cc3dbf7ba4f97369ff1731002000000000000000000000000fe0058b9e4df432cc3dbf7ba4f97369ff173100200000000000000000000000000000000000000000000000000d529b0f291e400000000000000000000000000000000000000000000000000000000000000000001001e84800000000000000000000000007903b8ce0ff4480e1c2496123b6623858be738e0000000000000000000000000000000000000000000000000000000',
    r: '0x79c55f7b33210a1098e5d72a6481b5762003b2f5a6349864ee8097b1ff9bd440',
    s: '0x3054093afd32637a9516752c3c29585d5e165772b6b5e4e5517f4c4b19302f3b',
    v: 0,
    creates: null,
    chainId: 43113,
    wait: [Function (anonymous)]
  },
  hash: '0x958e30ecbd90a4405616bfd3af6cb4f77f6a30852b174dccaadffcb6f505acac',
  receipt: {
    to: '0x7903B8CE0FF4480e1c2496123b6623858be738e0',
    from: '0x61a51662f0B30Bf176484cAc5B4a033C497cB2f3',
    contractAddress: null,
    transactionIndex: 0,
    gasUsed: BigNumber { _hex: '0x032d5d', _isBigNumber: true },
    logsBloom: '0x00004000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000400000800100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000002000000000000000000000000000000000000000000000000000000400000000000000000000008000080000000000000000000000000000000020000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000001000000000001000',
    blockHash: '0x3bb1b9536b9ba2cfdafc4a672fd3307b1ef7a741f822c9b17ea517368e6cc5bd',
    transactionHash: '0x13628d7ecc019c6e26e8936a34d59e344420906874c2f44c656680cad72b59db',
    logs: [ [Object] ],
    blockNumber: 18392691,
    confirmations: 4,
    cumulativeGasUsed: BigNumber { _hex: '0x032d5d', _isBigNumber: true },
    effectiveGasPrice: BigNumber { _hex: '0x062b85e900', _isBigNumber: true },
    status: 1,
    type: 2,
    byzantium: true
  }
}
```

**Comment by gabzim** [comment]
I haven't seen this reproduced with the new code. Closing for now, if this continues to happen please reopen.
